[LangOptions]
LanguageName=中文 + English
LanguageID=$0804
LanguageCodePage=0
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装 / Setup
SetupWindowTitle=安装 / Setup - %1
UninstallAppTitle=卸载 / Uninstall
UninstallAppFullTitle=%1 卸载 / Uninstall
InformationTitle=信息 / Information
ConfirmTitle=确认 / Confirm
ErrorTitle=错误 / Error
ButtonBack=< 上一步 / &Back
ButtonNext=下一步 / &Next >
ButtonInstall=安装 / &Install
ButtonOK=确定 / OK
ButtonCancel=取消 / Cancel
ButtonYes=是 / &Yes
ButtonNo=否 / &No
ButtonFinish=完成 / &Finish
ButtonBrowse=浏览 / &Browse...
ButtonWizardBrowse=浏览 / B&rowse...
ButtonNewFolder=新建文件夹 / &Make New Folder
ButtonYesToAll=全部是 / Yes to &All
ButtonNoToAll=全部否 / N&o to All
ExitSetupTitle=退出安装 / Exit Setup
ExitSetupMessage=安装尚未完成。现在退出将不会完成安装，稍后可重新运行安装程序。是否退出？%n%nSetup is not complete. You may run Setup again later. Exit Setup?
ClickNext=点击“下一步”继续，或“取消”退出。%nClick Next to continue, or Cancel to exit Setup.
WelcomeLabel1=欢迎安装 [name]%nWelcome to the [name] Setup Wizard
WelcomeLabel2=即将在电脑上安装 [name/ver]。建议先关闭其他应用程序。%n%nThis will install [name/ver] on your computer. Please close other applications before continuing.
WizardLicense=许可协议 / License Agreement
LicenseLabel=继续前请阅读以下重要信息。 / Please read before continuing.
LicenseLabel3=请阅读许可协议。必须同意协议条款才能继续安装。%nPlease read the License Agreement. You must accept its terms to continue.
LicenseAccepted=我同意协议 / I &accept the agreement
LicenseNotAccepted=我不同意协议 / I &do not accept the agreement
WizardInfoBefore=安装须知 / Before Installation
InfoBeforeLabel=继续前请阅读以下重要信息。 / Please read before continuing.
InfoBeforeClickLabel=准备好后，点击“下一步”。 / Click Next when ready.
WizardInfoAfter=安装说明 / Information
InfoAfterLabel=请阅读以下信息。 / Please read the following information.
InfoAfterClickLabel=准备好后，点击“下一步”。 / Click Next when ready.
WizardSelectDir=安装位置 / Destination Location
SelectDirDesc=将 [name] 安装在哪里？ / Where should [name] be installed?
SelectDirLabel3=将安装到以下文件夹。 / Setup will install into the following folder.
SelectDirBrowseLabel=点击“下一步”继续，或“浏览”更换文件夹。%nClick Next to continue, or Browse to choose a different folder.
DiskSpaceGBLabel=至少需要 [gb] GB 空闲空间。 / At least [gb] GB of free space is required.
DiskSpaceMBLabel=至少需要 [mb] MB 空闲空间。 / At least [mb] MB of free space is required.
BrowseDialogTitle=浏览文件夹 / Browse For Folder
BrowseDialogLabel=选择文件夹后点击确定。 / Select a folder, then click OK.
NewFolderName=新建文件夹 / New Folder
WizardReady=准备安装 / Ready to Install
ReadyLabel1=已准备好安装 [name]。 / Ready to install [name] on your computer.
ReadyLabel2a=点击“安装”开始，或“上一步”检查设置。%nClick Install to continue, or Back to review settings.
ReadyLabel2b=点击“安装”开始。 / Click Install to continue.
ReadyMemoDir=安装位置 / Destination location:
ReadyMemoType=安装类型 / Setup type:
ReadyMemoComponents=安装组件 / Selected components:
ReadyMemoGroup=开始菜单文件夹 / Start Menu folder:
ReadyMemoTasks=其他任务 / Additional tasks:
WizardPreparing=正在准备 / Preparing to Install
PreparingDesc=正在准备安装 [name]。 / Preparing to install [name].
CannotContinue=无法继续。点击“取消”退出。 / Setup cannot continue. Click Cancel to exit.
WizardInstalling=正在安装 / Installing
InstallingLabel=正在安装 [name]，请稍候。 / Please wait while Setup installs [name].
FinishedHeadingLabel=[name] 安装完成%nCompleting the [name] Setup Wizard
FinishedLabelNoIcons=[name] 已安装。打开 PowerPoint 的 LiquidSlide 选项卡即可使用。%n[name] is installed. Open the LiquidSlide tab in PowerPoint to begin.
FinishedLabel=[name] 已安装。打开 PowerPoint 的 LiquidSlide 选项卡即可使用。%n[name] is installed. Open the LiquidSlide tab in PowerPoint to begin.
ClickFinish=点击“完成”退出安装。 / Click Finish to exit Setup.
FinishedRestartLabel=需要重启电脑完成 [name] 安装。现在重启吗？%nRestart your computer to complete installation of [name]. Restart now?
FinishedRestartMessage=需要重启电脑完成 [name] 安装。现在重启吗？%nRestart your computer to complete installation of [name]. Restart now?
YesRadio=现在重启 / &Yes, restart now
NoRadio=稍后重启 / &No, restart later
StatusCreateDirs=正在创建文件夹 / Creating directories...
StatusExtractFiles=正在解压文件 / Extracting files...
StatusCreateIcons=正在创建快捷方式 / Creating shortcuts...
StatusCreateIniEntries=正在写入配置 / Creating INI entries...
StatusCreateRegistryEntries=正在写入注册表 / Creating registry entries...
StatusRegisterFiles=正在注册文件 / Registering files...
StatusSavingUninstall=正在保存卸载信息 / Saving uninstall information...
StatusRunProgram=正在完成安装 / Finishing installation...
StatusRollback=正在撤销更改 / Rolling back changes...
SetupAborted=安装未完成。请解决问题后重新运行安装程序。%nSetup was not completed. Please correct the problem and run Setup again.
SetupAlreadyRunning=安装程序已在运行。 / Setup is already running.
SetupFileCorrupt=安装文件已损坏，请重新下载安装包。 / Setup files are corrupted. Please download a new copy.
SetupFileMissing=安装文件 %1 缺失，请重新下载安装包。 / Setup file %1 is missing. Please download a new copy.
WindowsVersionNotSupported=不支持当前 Windows 版本。 / This Windows version is not supported.
OnlyOnTheseArchitectures=仅支持以下 Windows 处理器架构： / Supported Windows processor architectures:%n%n%1
ErrorCreatingDir=无法创建文件夹 / Unable to create directory "%1"
DiskSpaceWarningTitle=磁盘空间不足 / Not Enough Disk Space
DiskSpaceWarning=需要 %1 KB 空间，目前只有 %2 KB。仍要继续吗？%nRequires %1 KB, but only %2 KB is available. Continue anyway?
DirNameTooLong=文件夹路径过长。 / The folder path is too long.
InvalidDirName=文件夹名称无效。 / The folder name is not valid.
DirExistsTitle=文件夹已存在 / Folder Exists
DirExists=文件夹已存在，仍要安装到此处吗？ / Folder already exists. Install here anyway?%n%n%1
DirDoesntExistTitle=文件夹不存在 / Folder Does Not Exist
DirDoesntExist=文件夹不存在，是否创建？ / Folder does not exist. Create it?%n%n%1
InvalidDrive=所选驱动器不存在或无法访问，请另选位置。 / The selected drive does not exist or is inaccessible. Select another.
ErrorExecutingProgram=无法执行文件 / Unable to execute file:%n%1
ErrorCreatingTemp=无法在目标目录创建临时文件 / Error creating a temporary file:
ErrorCopying=复制文件失败 / Error copying a file:
ErrorReplacingExistingFile=替换已有文件失败 / Error replacing the existing file:
ExistingFileReadOnly2=无法替换只读文件。 / The existing file is read-only and cannot be replaced.
ExistingFileReadOnlyRetry=移除只读属性后重试 / &Remove read-only attribute and retry
ExistingFileReadOnlyKeepExisting=保留已有文件 / &Keep the existing file
AbortRetryIgnoreSelectAction=请选择操作 / Select action
AbortRetryIgnoreRetry=重试 / &Try again
AbortRetryIgnoreIgnore=忽略并继续 / &Ignore and continue
AbortRetryIgnoreCancel=取消安装 / Cancel installation
RetryCancelSelectAction=请选择操作 / Select action
RetryCancelRetry=重试 / &Try again
RetryCancelCancel=取消 / Cancel
ConfirmUninstall=确定移除 %1 及所有组件吗？%nAre you sure you want to remove %1 and all its components?
UninstallStatusLabel=正在移除 %1，请稍候。 / Please wait while %1 is removed.
UninstalledAll=%1 已成功卸载。 / %1 was successfully removed.
UninstalledMost=%1 卸载完成，部分文件需手动删除。%n%1 uninstall complete. Some items must be removed manually.
UninstalledAndNeedsRestart=需要重启电脑完成 %1 卸载。现在重启吗？%nRestart your computer to complete removal of %1. Restart now?
WizardUninstalling=正在卸载 / Uninstall Status
StatusUninstalling=正在卸载 %1 / Uninstalling %1...
UninstallNotFound=找不到文件 %1，无法卸载。 / File %1 is missing. Cannot uninstall.
UninstallOpenError=无法打开文件 %1，无法卸载。 / Cannot open file %1. Cannot uninstall.
UninstallDataCorrupted=卸载文件 %1 已损坏。 / Uninstall file %1 is corrupted.
